# Generated by Django 5.0.2 on 2024-02-13 17:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_coin_ucoin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tbalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='ucoin',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ucoin',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ucoin',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='info',
            field=models.TextField(default='deposit information', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ucoin',
            name='info',
            field=models.TextField(default='deposit information', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ucoin',
            name='logo',
            field=models.ImageField(upload_to='ucoinimg/%y'),
        ),
        migrations.AddField(
            model_name='ucoin',
            name='balance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.tbalance'),
            preserve_default=False,
        ),
    ]
