# Generated by Django 5.0.2 on 2024-02-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_backup_logo_alter_coin_logo_alter_ucoin_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depht',
            name='deposit',
            field=models.FloatField(default=0.0),
        ),
    ]
