# Generated by Django 5.0.2 on 2024-02-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_deposit_depht_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='depht',
            name='status',
            field=models.FloatField(default=False),
        ),
    ]
