# Generated by Django 5.0.2 on 2024-02-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_depht_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depht',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
