# Generated by Django 5.0.2 on 2024-02-15 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_depht_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='depht',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
