# Generated by Django 5.0.2 on 2024-02-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_depht_ucoin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depht',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='depht',
            name='date',
        ),
    ]
