# Generated by Django 5.0.2 on 2024-02-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_depht_amount_remove_depht_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='depht',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
