# Generated by Django 5.0.2 on 2024-02-15 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_backup_date_backt'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
