# Generated by Django 5.0.2 on 2024-02-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_withdh'),
    ]

    operations = [
        migrations.AddField(
            model_name='depht',
            name='max',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='depht',
            name='min',
            field=models.IntegerField(default=10),
        ),
    ]
