# Generated by Django 5.0.2 on 2024-02-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_depht_max_depht_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depht',
            name='max',
        ),
        migrations.RemoveField(
            model_name='depht',
            name='min',
        ),
        migrations.AddField(
            model_name='ucoin',
            name='max',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='ucoin',
            name='min',
            field=models.IntegerField(default=10),
        ),
    ]
