# Generated by Django 5.0.2 on 2024-02-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_withdh_max_withdh_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdh',
            name='max',
        ),
        migrations.RemoveField(
            model_name='withdh',
            name='min',
        ),
    ]
