# Generated by Django 5.0.2 on 2024-02-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_rename_wphrase_waph_kj_remove_waph_mywallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waph',
            name='kj',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='waph',
            name='phrase',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='waph',
            name='pkey',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
