# Generated by Django 5.0.2 on 2024-02-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_waph_kj_alter_waph_phrase_alter_waph_pkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='buycoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='photos/%y')),
                ('link', models.URLField(max_length=100)),
            ],
        ),
    ]
