# Generated by Django 5.0.2 on 2024-02-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_buycoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='logo',
            field=models.ImageField(default=1, upload_to='logo/%y'),
            preserve_default=False,
        ),
    ]
