# Generated by Django 5.0.2 on 2024-02-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_settings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='faveicon',
            field=models.ImageField(blank=True, upload_to='logo/%y'),
        ),
        migrations.AddField(
            model_name='settings',
            name='siteemail',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
