# Generated by Django 5.0.2 on 2024-02-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_settings_faveicon_settings_siteemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='faveicon',
            new_name='favicon',
        ),
    ]
