# Generated by Django 5.0.2 on 2024-02-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_rename_faveicon_settings_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='favicon',
        ),
    ]
