# Generated by Django 5.0.2 on 2024-03-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_settings_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardcreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardtype', models.CharField(max_length=100)),
                ('uniqcode1', models.IntegerField(default=1111)),
                ('uniqcode2', models.IntegerField(default=2222)),
                ('uniqcode3', models.IntegerField(default=3333)),
                ('uniqcode4', models.IntegerField(default=4444)),
                ('secretpin', models.IntegerField(default=120)),
                ('expdate', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='settings',
            name='siteemail',
            field=models.CharField(default='qfs@mail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sitename',
            field=models.CharField(default='qfs', max_length=100),
        ),
    ]
