# Generated by Django 5.0.2 on 2024-03-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_cardcreate_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcreate',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
