# Generated by Django 5.0.2 on 2024-03-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_cardpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpay',
            name='paymentmethod',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
