# Generated by Django 5.0.2 on 2024-03-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_cardpay_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photos/%y')),
                ('reason', models.CharField(max_length=1000)),
                ('percentage', models.IntegerField(default=1)),
                ('raised', models.FloatField(default=0.0)),
                ('goal', models.FloatField(default=0.0)),
            ],
        ),
    ]
