# Generated by Django 5.0.2 on 2024-03-24 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_charity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='charitypayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=100)),
                ('cryptoname', models.CharField(default='n/a', max_length=100)),
                ('cryptoamount', models.FloatField(default=0.0)),
                ('giftcardname', models.CharField(max_length=100)),
                ('giftcardcode', models.IntegerField(blank=True)),
                ('giftcardamount', models.FloatField(default=0.0)),
                ('giftcardimg', models.ImageField(upload_to='photos/%y')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
