# Generated by Django 5.0.2 on 2024-03-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_charitypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitypayment',
            name='giftcardcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
