# Generated by Django 5.0.2 on 2024-03-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_alter_charitypayment_giftcardcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitypayment',
            name='giftcardamount',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
