# Generated by Django 5.0.2 on 2024-03-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_alter_charitypayment_giftcardamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitypayment',
            name='giftcardamount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
