# Generated by Django 5.0.2 on 2024-03-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_remove_charitypayment_giftcardamount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='giftcardpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giftcardname', models.CharField(max_length=100)),
                ('giftcardcode', models.IntegerField()),
                ('giftcardamount', models.FloatField()),
                ('giftcardimg', models.ImageField(upload_to='')),
            ],
        ),
    ]
