# Generated by Django 5.0.2 on 2024-03-25 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_giftcardpay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charitypayment',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giftcardpay',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giftcardpay',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
