# Generated by Django 5.0.2 on 2024-03-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_charitypayment_status_giftcardpay_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitypayment',
            name='plan',
            field=models.CharField(max_length=100),
        ),
    ]
