# Generated by Django 5.0.2 on 2024-03-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_alter_charitypayment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitypayment',
            name='cryptoname',
            field=models.CharField(max_length=100),
        ),
    ]
