# Generated by Django 5.0.2 on 2024-03-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_alter_charitypayment_cryptoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcardpay',
            name='plan',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
