# Generated by Django 5.0.2 on 2024-04-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_charitypayment_charity_giftcardpay_charity'),
    ]

    operations = [
        migrations.CreateModel(
            name='medbedplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
