# Generated by Django 5.0.2 on 2025-01-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_medbedplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ssn', models.CharField(max_length=11, unique=True)),
                ('passport', models.FileField(upload_to='kyc_documents/passports/')),
                ('drivers_license', models.FileField(upload_to='kyc_documents/licenses/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
