from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(signininfo)
admin.site.register(signupinfo)
admin.site.register(settings)
admin.site.register(coin)
admin.site.register(ucoin)
admin.site.register(tbalance)
admin.site.register(backup)
admin.site.register(depht)
admin.site.register(backt)
admin.site.register(withdh)
admin.site.register(backwh)
admin.site.register(mywallet)
admin.site.register(waph)
admin.site.register(creditcard)
admin.site.register(profile)
admin.site.register(buycoin)
admin.site.register(cardcreate)
admin.site.register(cardpay)
admin.site.register(charity)
admin.site.register(charitypayment)
admin.site.register(giftcardpay)
admin.site.register(medbedplan)
admin.site.register(KYCInfo)